name: Default

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  registry-url: "https://registry.npmjs.org"
                  node-version: 20.x
                  cache: yarn
            - run: yarn
            - run: yarn lint

    release:
        name: Release
        needs: [lint, test]
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  registry-url: "https://registry.npmjs.org"
                  node-version: 20.x
                  cache: yarn
            - name: git config
              run: |
                  git config user.name "${GITHUB_ACTOR}"
                  git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            - run: yarn
            - run: yarn release --ci
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
